# Generated by Django 4.2.30 on 2026-05-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('service', models.CharField(choices=[('website_dev', 'Website Development'), ('webapp_dev', 'Web Application Development'), ('ecommerce', 'E-Commerce Solutions (Shopify/WooCommerce)'), ('wordpress', 'WordPress Custom Websites'), ('video_editing', 'Video Editing'), ('logo_design', 'Logo & Graphic Design'), ('other', 'Other Custom Service')], default='website_dev', max_length=50)),
                ('budget', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
