# Generated by Django 4.2.30 on 2026-05-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectlead",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectlead",
            name="source_page",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="projectlead",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projectlead",
            name="service",
            field=models.CharField(
                choices=[
                    ("custom_erp", "Custom ERP Software"),
                    ("saas_dev", "SaaS Product Development"),
                    ("enterprise_web", "Enterprise Web Application"),
                    ("crm_dev", "CRM Development"),
                    ("startup_mvp", "Startup MVP Development"),
                    ("hrms_ai", "HRMS and Recruitment AI Platform"),
                    ("ai_automation", "AI Automation Solutions"),
                    ("ai_chatbot", "AI Chatbot or AI Agent"),
                    ("dashboard_analytics", "Dashboard and Analytics System"),
                    ("workflow_automation", "Workflow Automation System"),
                    ("mobile_app", "Mobile App Development"),
                    ("cloud_devops", "Cloud and DevOps Infrastructure"),
                    ("api_integrations", "API Development and Integrations"),
                    ("custom_software", "Custom Software Solution"),
                ],
                default="custom_erp",
                max_length=50,
            ),
        ),
    ]
